eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH=$PATH:~/.local/bin/
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
autoload -U compinit; compinit
zstyle ':completion:*' menu select
alias shrl="source ~/.zshrc"
cd ()
{
    if [ -n "$1" ]; then
    builtin cd "$@" && ls
    else
    builtin cd ~ && ls
    fi
}

# Machine-specific plugins and aliases, generated by install.sh
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
