# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FDFAED
background         #212625
cursor             #AAA698

active_tab_foreground     #212625
active_tab_background     #FDFAED
inactive_tab_foreground   #FDFAED
inactive_tab_background   #212625

active_border_color   #FDFAED
inactive_border_color #212625
bell_border_color     #0F211F

color0      #474C4B
color1		#0F211F
color2		#403D31
color3		#403D31
color4		#745037
color5		#AD7B51
color6		#BBB499
color7		#F4EFDD
color8		#ABA79B
color9		#132C29
color10		#565242
color11		#565242
color12		#9B6B49
color13		#E7A46C
color14		#FAF0CC
color15		#F4EFDD
